sonar.projectKey=John361_ansible-vault-secrets
sonar.organization=john361
sonar.sources=.
sonar.exclusions="**/.ansible/**,**/.venv/**,**/*.pb.go"
sonar.rust.clippy.report_path=clippy.json
sonar.python.version=3.14
sonar.python.coverage.reportPaths=coverage.xml
