name: Release

on:
  push:
    tags:
      - v[0-9]+.*
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "The version to deploy"
        required: true

permissions:
  contents: write
  id-token: write
  actions: write
  pages: write

jobs:
  release:
    name: Release to Ansible Galaxy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@751276eafca55f10f252026015f43c488f2322ba
        with:
          python-version: "3.14"

      - name: Setup uv
        uses: astral-sh/setup-uv@19b4d1e990bec64818914c40230bde93a0de300b
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          working-directory: "./"

      - name: Setup Ansible
        run: |
          uv sync --frozen --no-build

      - name: Generate changelog
        run: |
          uv run --frozen --no-build antsibull-changelog release

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@4b4693c596717de5c939cfa92b1b0b5c8676537f
        with:
          commit_message: Update changelog
          file_pattern: CHANGELOG.md
          branch: ${{ github.event.pull_request.head.ref || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Ansible Build
        run: |
          uv run --frozen --no-build ansible-galaxy collection build --force
          echo "ARTIFACT_NAME=$(ls *.tar.gz)" >> ${GITHUB_ENV}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@e5ee6bc58a36b838b92fc1217f2e4b414b5abcc8
        with:
          files: ${{ env.ARTIFACT_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Ansible Galaxy
        run: |
          uv run --frozen --no-build ansible-galaxy collection publish ${{ env.ARTIFACT_NAME }} \
            --token ${ANSIBLE_GALAXY_TOKEN}
        env:
          ANSIBLE_GALAXY_TOKEN: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
